### ISSUE TITLE
commonJS module (pouchdb-authentication) not importing correctly

### ISSUE THREAD

**Issue by svametcalf** [rwjblue/ember-cli-cjs-transform#18]
I am writing an addon for adding [pouchdb-authentication](https://github.com/pouchdb-community/pouchdb-authentication) to ember-simple-auth. I am attempting to import pouchdb-authentication as a CommonJS module. 

I have done the following: 

```shell
npm install --save pouchdb-authentication
```

In my `index.js`, I have added the following hook: 
```javascript
included(app){
  app.import('node_modules/pouchdb-authentication/lib/index.js', {
    using: [
      {transform: 'cjs', as: 'pouchdb-authentication'}
    ]
  }
}
```

When I attempt to use the module in a class, ie `from PouchDBAuthentication import 'pouchdb-authentication`, I get the following error: 

```
Error: Could not find module `util` imported from `pouchdb-authentication`
at missingModule (http://localhost:7357/assets/vendor.js:252:11)
at findModule (http://localhost:7357/assets/vendor.js:263:7)
at Module.findDeps (http://localhost:7357/assets/vendor.js:173:24)
at findModule (http://localhost:7357/assets/vendor.js:267:11)
at Module.findDeps (http://localhost:7357/assets/vendor.js:173:24)
at findModule (http://localhost:7357/assets/vendor.js:267:11)
at requireModule (http://localhost:7357/assets/vendor.js:29:15)
at Class._extractDefaultExport (http://localhost:7357/assets/vendor.js:99921:20)
at Class.resolveOther (http://localhost:7357/assets/vendor.js:99621:32)
at Class.superWrapper [as resolveOther] (http://localhost:7357/assets/vendor.js:54195:22)
```

Any idea what is going on here? It does not look like `util` is an imported dependency in pouchdb-authentication.

**Comment by Turbo87** [comment]
The `util` module is imported from https://github.com/isaacs/inherits/blob/master/inherits.js#L2, and is usually a built-in module of Node.js. `ember-browserify` has some shims for that, but this transform does not. `inherits` should switch over to a browser-compatible version, but you have probably tried this on a version of a transform that did not include https://github.com/rwjblue/ember-cli-cjs-transform/pull/17 yet, which should fix your issue.

**Comment by svametcalf** [comment]
I am now getting the following error, after upgrading to 1.2: 

```
Error: Could not find module `events` imported from `pouchdb-authentication`
    at missingModule (http://localhost:7357/assets/vendor.js:252:11)
    at findModule (http://localhost:7357/assets/vendor.js:263:7)
    at Module.findDeps (http://localhost:7357/assets/vendor.js:173:24)
    at findModule (http://localhost:7357/assets/vendor.js:267:11)
    at Module.findDeps (http://localhost:7357/assets/vendor.js:173:24)
    at findModule (http://localhost:7357/assets/vendor.js:267:11)
    at requireModule (http://localhost:7357/assets/vendor.js:29:15)
    at Class._extractDefaultExport (http://localhost:7357/assets/vendor.js:100142:20)
    at Class.resolveOther (http://localhost:7357/assets/vendor.js:99842:32)
    at Class.superWrapper [as resolveOther] (http://localhost:7357/assets/vendor.js:54195:22)
```

Any ideas?
