### ISSUE TITLE
CJS Transform - Unexpected token: /ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:199:15

### ISSUE THREAD

**Issue by Sticksword** [rwjblue/ember-cli-cjs-transform#249]
Having similar issue to [this](https://github.com/rwjblue/ember-cli-cjs-transform/issues/45) but have imported `rollup-plugin-node-builtins` module as described in the readme.

`ember-cli-build.js` looks like this:
```
  const nodeBuiltins = require('rollup-plugin-node-builtins');
  app.import('node_modules/googleapis/build/src/index.js', {
    using: [
      { transformation: 'cjs', as: 'googleapis', plugins: [ nodeBuiltins() ] }
    ]
  });
```

Full stack trace:

```
=================================================================================

ENV Summary:

  TIME: Tue Jul 23 2019 04:28:49 GMT-0700 (Pacific Daylight Time)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node/12.5.0/bin/node
  - /usr/local/Cellar/node/12.5.0/bin/ember
  - s
  EXEC_PATH: /usr/local/Cellar/node/12.5.0/bin/node
  TMPDIR: /var/folders/m3/_vjwm8gx1kz67xbq5w4vgk_000048w/T
  SHELL: /bin/zsh
  PATH:
  - /usr/local/Cellar/node/12.5.0/bin
  - /usr/local/Cellar/node/11.14.0/bin
  - /Users/michaelchen/.yarn/bin
  - /Users/michaelchen/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /opt/local/bin
  ... (Python, etc.)
  PLATFORM: darwin x64
  FREEMEM: 36102144
  TOTALMEM: 17179869184
  UPTIME: 3345448
  LOADAVG: 6.83544921875,4.68798828125,5.5068359375
  CPUS:
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 4
  - nghttp2: 1.34.0
  - node: 10.16.0
  - openssl: 1.1.1b
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.52
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Unexpected token
    at error (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:199:15)
    at Module.error (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:17170:9)
    at tryParse (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:16845:16)
    at Module.setSource (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:16910:33)
    at /Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:20699:20
  - code: [undefined]
  - codeFrame: Unexpected token
  - errorMessage: Unexpected token
        at CJSTransform (CJS Transform)
-~- created here: -~-
    at new Plugin (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/broccoli-plugin/index.js:7:31)
    at new CJSTransform (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/src/cjs-transform.js:14:5)
    at Object.transform [as callback] (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/src/index.js:18:27)
    at DefaultPackager.applyCustomTransforms (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/default-packager.js:334:57)
    at DefaultPackager.processAppAndDependencies (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/default-packager.js:249:27)
    at DefaultPackager.packageJavascript (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/default-packager.js:1296:32)
    at EmberApp._legacyPackage (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1773:48)
    at EmberApp.toTree (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1819:27)
    at module.exports (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/ember-cli-build.js:42:14)
    at Builder.readBuildFile (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/models/builder.js:51:14)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Unexpected token
        at CJSTransform (CJS Transform)
-~- created here: -~-
    at new Plugin (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/broccoli-plugin/index.js:7:31)
    at new CJSTransform (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/src/cjs-transform.js:14:5)
    at Object.transform [as callback] (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/src/index.js:18:27)
    at DefaultPackager.applyCustomTransforms (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/default-packager.js:334:57)
    at DefaultPackager.processAppAndDependencies (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/default-packager.js:249:27)
    at DefaultPackager.packageJavascript (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/default-packager.js:1296:32)
    at EmberApp._legacyPackage (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1773:48)
    at EmberApp.toTree (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1819:27)
    at module.exports (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/ember-cli-build.js:42:14)
    at Builder.readBuildFile (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli/lib/models/builder.js:51:14)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: CJS Transform
  - nodeName: CJSTransform
  - originalErrorMessage: Unexpected token
  - stack: Error: Unexpected token
    at error (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:199:15)
    at Module.error (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:17170:9)
    at tryParse (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:16845:16)
    at Module.setSource (/Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:16910:33)
    at /Users/michaelchen/Development/misc-dev/dummy-chrome-extension/timeline-project/node_modules/ember-cli-cjs-transform/node_modules/rollup/dist/rollup.js:20699:20

=================================================================================
```

**Comment by Sticksword** [comment]
Using version 
```
    "ember-cli-cjs-transform": {
      "version": "1.3.1",
      ...
```

**Comment by Sticksword** [comment]
`ember -v` output:

```
ember-cli: 3.10.1
node: 10.16.0
os: darwin x64
```
