### ISSUE TITLE
Seems to get tripped up on json files?

### ISSUE THREAD

**Issue by LeviDooley** [rwjblue/ember-cli-cjs-transform#59]
I was trying to import `aws-iot-device-sdk`. Building the ember app seemed to cause the cjs transform to break on the package.json file. 

```javascript
  // ember-cli-build.js
  app.import('node_modules/aws-iot-device-sdk/index.js', {
    using: [{ transformation: 'cjs', as: 'aws-iot-device-sdk' }]
  });
```

```
Build Error (CJSTransform) in .\node_modules\aws-iot-device-sdk\package.json:2:9

Unexpected token


Stack Trace and Error Report: error.dump.33b66b51326596af4144536855e8fd81.log
preferring built-in module 'events' over local alternative at '.\node_modules\events\events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
```

I'm using a Windows computer by the way in case that is important.

**Comment by rwjblue** [comment]
Can you share the contents of that file?

**Comment by LeviDooley** [comment]
This file `error.dump.33b66b51326596af4144536855e8fd81.log`? Sure.

```=================================================================================

ENV Summary:

  TIME: Thu Jun 28 2018 17:14:04 GMT-0500 (Central Daylight Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\Stick Figure\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - s
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\LEVIDO~1\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Users\Stick Figure\bin;C
  - \Program Files\Git\mingw64\bin;C
  - \Program Files\Git\usr\local\bin;C
  - \Program Files\Git\usr\bin;C
  - \Program Files\Git\usr\bin;C
  - \Program Files\Git\mingw64\bin;C
  - \Program Files\Git\usr\bin;C
  - \Users\Stick Figure\bin;C
  - \Program Files (x86)\Common Files\Oracle\Java\javapath;C
  - \ProgramData\Oracle\Java\javapath;C
  - \Program Files (x86)\Intel\iCLS Client;C
  - \Program Files\Intel\iCLS Client;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\PuTTY;C
  - \Program Files\Git\cmd;C
  - \Program Files\Redis;C
  - \Program Files\nodejs;C
  - \ffmpeg-20171204-71421f3-win64-static\bin;C
  - \Program Files\Intel\WiFi\bin;C
  - \Program Files\Common Files\Intel\WirelessCommon;C
  - \WINDOWS\System32\OpenSSH;C
  - \Program Files\Mozilla Firefox;C
  - \Program Files (x86)\GnuWin32\bin;C
  - \Python27;C
  - \Python27\Scripts;C
  - \MinGW\bin;C
  - \Program Files\CMake\bin;C
  - \Users\Stick Figure\AppData\Local\Microsoft\WindowsApps;C
  - \Program Files\Microsoft VS Code\bin;C
  - \Users\Stick Figure\AppData\Roaming\npm;C
  - \Program Files\Git\usr\bin\vendor_perl;C
  - \Program Files\Git\usr\bin\core_perl
  PLATFORM: win32 x64
  FREEMEM: 1222557696
  TOTALMEM: 12763435008
  UPTIME: 914477.1948507
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz - 2904
  - Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz - 2904
  - Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz - 2904
  - Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz - 2904
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.1
  - openssl: 1.0.2m
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.47
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Unexpected token
    at error (C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:199:15)
    at Module.error (C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:17170:9)
    at tryParse (C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:16845:16)
    at Module.setSource (C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:16910:33)
    at C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:20699:20
    at <anonymous>
  - codeFrame: Unexpected token
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `CJSTransform` plugin. 💥
Unexpected token
  - errorType: Build Error
  - location:
    - column: 9
    - file: C:\Users\Stick Figure\DevStuff\ember_project\node_modules\aws-iot-device-sdk\package.json
    - line: 2
  - message: Build Canceled: Broccoli Builder ran into an error with `CJSTransform` plugin. 💥
Unexpected token
  - name: Error
  - nodeAnnotation: CJS Transform
  - nodeName: CJSTransform
  - originalErrorMessage: Unexpected token
  - stack: Error: Unexpected token
    at error (C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:199:15)
    at Module.error (C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:17170:9)
    at tryParse (C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:16845:16)
    at Module.setSource (C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:16910:33)
    at C:\Users\Stick Figure\DevStuff\ember_project\node_modules\ember-cli-cjs-transform\node_modules\rollup\dist\rollup.js:20699:20
    at <anonymous>

=================================================================================
```

**Comment by griffithsbs** [comment]
I had a similar issue with a sub-dependency requiring a JSON file from its package. Installing [rollup-plugin-json](https://github.com/rollup/rollup-plugin-json) looks like it's working for me. You'd need to declare the plugin like so:

```javascript
const json_plugin = require('rollup-plugin-json');
app.import('node_modules/aws-iot-device-sdk/index.js', {
  using: [{ transformation: 'cjs', as: 'aws-iot-device-sdk', 'plugins': [ json_plugin() ]  }]
});
```

**Comment by rwjblue** [comment]
Thanks @griffithsbs! Going to close for now (happy to reopen if that isn't the solution)...
